//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOCATION_DES_VOITURES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modele
    {
        public int idm { get; set; }
        public string NomMarque { get; set; }
        public string Serie { get; set; }
    
        public virtual Voiture Voiture { get; set; }
    }
}
