//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOCATION_DES_VOITURES
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int idres { get; set; }
        public Nullable<int> idc { get; set; }
        public Nullable<int> idv { get; set; }
        public string type_res { get; set; }
        public Nullable<System.DateTime> date_debut { get; set; }
        public Nullable<System.DateTime> date_fin { get; set; }
        public string is_valid { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Voiture Voiture { get; set; }
    }
}
