//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOCATION_DES_VOITURES
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Voiture
    {
        public int idv { get; set; }
        public string NumeroMatricule { get; set; }
        [Required]
        [Column(TypeName = "date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> DateCirculation { get; set; }
        public string Carburant { get; set; }
        public Nullable<double> Prix { get; set; }
        public string Vimage { get; set; }
        public Nullable<int> idcat { get; set; }
        public Nullable<int> idm { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual Modele Modele { get; set; }
        public virtual reservation reservation { get; set; }
    }
}
